### ISSUE TITLE
WiFi Password

### ISSUE THREAD

**Issue by SequentialOne** [ohAnd/dtuGateway#10]
Hello,
only 32 characters are possible for the wifi password.
Is it possible to extend the password to 63 characters (full length)
Would be great
Best regards

**Comment by ohAnd** [comment]
Hi, sorry, it seems I have some notification issues... ;-)

I've changed the length of ssid's and wifi passwords to a maximum length of 64 characters. See the current dev branch.
Please give a short feedback if it works as excpected.

**Comment by SequentialOne** [comment]
No Problem,
thank you for your work, but how do i install it ?
I´m not a "pro" in that :/
It was easy with the bin file me ;)

**Comment by SequentialOne** [comment]
Yes it is possible ;-) I had "tomatoes on my eyes" or my "brain was out of service".... 
Thank you.... :-)
