### ISSUE TITLE
Question: what is "dtu host IP in your local network:"?

### ISSUE THREAD

**Issue by hirbelo** [ohAnd/dtuGateway#16]
Hello,
 very nice project. 
I would also like to read out the values ​​of the inverter. 

But what should be entered in “dtu host IP in your local network:”? 

The inverter has its own WiFi and doesn't know my local network.
Gruß Oli

**Comment by ohAnd** [comment]
Hi @hirbelo ,

that is the IP of the Hoymiles Inverter inside your local wifi - should be discoverable over your router.

The inverter has to wifi connections one for the own AccessPoint that you can reach with the hoymilesInstaller app and the other one connects with your wifi to reach the hoymiles servers (if you want). Should be done in the installation process of your inverter.
The second one gets the needed IP from your router.

Gruss
Andreas

**Comment by hirbelo** [comment]
OK, thanks @ohAnd  for the quick reply.
I don't have an installation.
I'm currently looking at the values ​​via the S-Miles app without a user account - so only via inverter's own access point.
Do I understand correctly - I can't use the project without an S-Miles account?

**Comment by ohAnd** [comment]
Hi @hirbelo ,

no, there is usually no S-Miles account directly needed.
The usual installation is something like this:

inverter <-> local wifi <-> internet <-> hoymiles server
                      local wifi <-> dtu gateway
in parallel it is possible over the served Accesspoint of the inverter
inverter <-> your smartphone/ tablet (S-Miles Installer App)

Therefore the dtugateway connects directly with the inverter, only in the internal network and without any external connection.

"But" in my experiences the first installation needs this account to connect the inverter with your local wifi... to make it available in the local network and also to get firmware updates by hoymiles.

Hope it answers your question.

**Comment by h0pless** [comment]
> no, there is usually no S-Miles account directly needed. The usual installation is something like this:
> 
> inverter <-> local wifi <-> internet <-> hoymiles server local wifi <-> dtu gateway in parallel it is possible over the served Accesspoint of the inverter inverter <-> your smartphone/ tablet (S-Miles Installer App)
> 
> Therefore the dtugateway connects directly with the inverter, only in the internal network and without any external connection.
> 
> "But" in my experiences the first installation needs this account to connect the inverter with your local wifi... to make it available in the local network and also to get firmware updates by hoymiles.

I have a follow-up question, sorry for using the old issue. The documentation reads:
>Communication happens directly to the inverter's internal DTU over Wi-Fi

And there are options to provide the dtu gateway with the ssid and password for the inverters wireless network. I have configured these but the inverter itself is not connected to the main wireless network, only the dtu gateway is.

Is this setup supported? 
My dtu gateway does not seem to be able to connect to the inverter.
