### ISSUE TITLE
Verbindung zu Home Assistant über MQTT nicht möglich

### ISSUE THREAD

**Issue by denkandich** [ohAnd/dtuGateway#26]
Hallo,
habe einen Home Assistant 12.3 auf einem Synology in einer VM laufen. Habe einen HMS-800W-2T auf einem 286 installiert und ich bekomme die Werte von meinem Hoymiles. Wollte jetzt über MQTT die Daten zu meinem Home Assitant schicken, aber das funktioniert nicht. Mein Tasmote Zähler funktioniert, und mein HMS-1600 bringt auch seine Daten an den MQTT. Habe erst die Version 1.5.0006 versucht und dann den letzten Snapshot 1.5.0037. Bei beiden bekomme ich keine Daten, richtiger User und PW. Habe mir jetzt den MQTT Explorer installiert und hier sehe ich keinerlei Daten die vom dem HMS-800 kommen würden.
Also was mache ich falsch, eigentlich sollte die xxx37 da ja sauber funktioenren.

**Comment by ohAnd** [comment]
Hi @denkandich ,

MQTT läuft bei mir in meiner "einfachen" Testumgebung ohne HA... soweit auch stabil. 
(btw. aktuell sind snapshot und release inhaltlich gleich) 

Kannst du bitte prüfen, ob deine IP und Port zu deinem Broker korrekt eingetragen sind und damit auch gespeichert wurden. Ggfs. einfach die Webseite neu laden, damit die tatsächlich gespeicherten Daten im settings Bereich zu sehen sind.

Weitere Analyse... ESP an USB an Rechner und mit Serial Monitor die Outputs anschauen. Hier sollte nach dem Reboot die Meldung Mqtt connected sichtbar werden, bzw. wiederholend der Versuch zu verbinden, wenn die Verbindung noch nicht steht...

BR

**Comment by denkandich** [comment]
Hallo,habe jetzt festgestellt, über den MQTT Explorer kommen Meldungen under dem Label HMS800. Aber der Home Assistant ignoriert dies, ich kann es nicht einrichten. Den HMS1600 und den Tasmoto Zähler hat er gefunden und auch eingerichtet. Im MQTT sagt er nur 2 Geräte und der HMS800 wird nicht gefunden. Kann man den irgendwie noch einrichten, Meldungen kommen vom HSM800.

**Comment by ohAnd** [comment]
Hi! 

Was meinst du mit 'HMS800'? Ist das die main topic anstelle von 'dtu1' (default), die du in den Einstellungen von dtuGateway angegeben hast?

Kann dir hier leider nicht folgen... Vielleicht kannst du einen Screenshot von deinen Einstellungen bzgl Mqtt Binding posten... Also IP Port main topic... 

Mir ist aus deiner Info noch nicht ganz klar, ob tatsächlich Daten vom dtuGateway bei deinem Broker ankommen. 

Gruss

**Comment by denkandich** [comment]
HMS800 habe ich in die Main Topic eingetragen, im MQTT Explorer sehe ich die MQTT Meldung unter dem Reiter HMS800. Einstellungen habe ich die IP-Adresse von meinem NAS wo die virtuelle Maschine der HomeAssistant läuft. 192.168.178.10:1883
User ist der mqtt-user und das eingerichtete PW im MQTT. und der main Topic habe ich schon vieles getestet.

**Comment by ohAnd** [comment]
Dann scheint ja die Verbindung vom dtuGateway zu deinem Broker i.O. zu stehen ...
HA seitig kann ich da leider nicht helfen, aber vielleicht wissen ja @Lassa333 oder @smarthomehomebase hier weiter ?
(ich denke, hier muss es neben der AutoDiscovery -> vgl. #22 , auch eine manuelle Config geben, um dem HA für das entsprechende item (hier der Inverter) die mqtt topic und deren Inhalt zum mapping mitzugeben)

**Comment by Lassa333** [comment]
@ denkandich: 

Ich fasse nochmal kurz deine Situation zusammen:

*	Dein HMS-800W-2T Inverter sendet die Daten in dein Wlan
*	Du hast einen ESP8266 mit der FW 1.5.0037 stabil in deinem Wlan am Laufen
*	In der FW ist MQTT aktiviert, Dein MQTT-Topic hast du „HMS800“ benannt, User und Passwort sind gesetzt
*	In deiner HA Instanz empfängt der MQTT-Explorer auch die Inverter-Daten im Topic „HMS800“  

Dein Problem: Du „siehst“ die Inverter-Daten, kannst sie aber weder speichern noch nutzen: hab ich das richtig zusammengefasst?

Wenn dem so ist, füge deiner „configuration.yaml“ folgendes hinzu:



Anmerkung: Formatierung bitte genauso übernehmen + „dtu1“ musst du mit „HMS800“ ersetzten 

Das erzeugt 3 neue „Sensoren“ (Gesamtertrag, Tages-Ertrag, aktueller Ertrag des Grids), deren Werte HA für 10 Tage speichert. Und du kannst die Werte auswerten, anzeigen, ins Dashboard einbinden usw. – Eben dass, was man halt so haben will 😉

Ich hoffe, das löst dein Problem

BR

Lassa333

**Comment by denkandich** [comment]
Hallo, danke für die Rückmeldung, irgendwie fehlen in deiner Nachricht die Einträge, kann das sein ?.

**Comment by denkandich** [comment]
Irgendwie sehe ich den Anhang nicht, mache ich was falsch, bin angemeldet.

**Comment by denkandich** [comment]
<img width="345" alt="datei" src="https://github.com/ohAnd/dtuGateway/assets/139382297/d51ff755-295a-440d-9692-90676c2f1d02">
Habe es eingetragen, aber es funktioniert nicht. Keine Ahnung warum

**Comment by denkandich** [comment]
Die Topic habe ich natürlich auf dtu1 gestellt.

**Comment by denkandich** [comment]
Danke für die Geduld, habe es formatiert, aber der Sensor wird nicht angezeigt. Hier mal was im MQTT Explorer kommt.
<img width="317" alt="mqttexplorer" src="https://github.com/ohAnd/dtuGateway/assets/139382297/4fa81748-8582-44c1-8371-c2ebd0310506">
Keine Ahnung was ich noch machen soll. Der HMS1600 und mein Tasmota für meinen Stromzähler wurden sofort erkannt. Langsam verliere ich die Geduld. Dir eine sehr großes Danke.

**Comment by Lassa333** [comment]
Ohje! So aus der Ferne ist das echt nicht so leicht 

Vielleicht als letzten Versuch: Kopier dir mal den Inhalt der Beispiel yaml von dieser Seite ( https://www.home-assistant.io/integrations/sensor.mqtt/ ) in deine yaml. Tausche dann einfach "home/bedroom/temperature" gegen "dtu1/grid/totalEnergy" aus und versuchs nochmal.

**Comment by smarthomehomebase** [comment]
Hat bei mir auch erst nicht funktioniert, dann habe ich in den bindungs bei mqtt main topic for this dtu den / entfernt. Das hat zum Erfolg geführt.
![homeass](https://github.com/ohAnd/dtuGateway/assets/145500978/a607d65b-97aa-48a1-bcf1-4fc205993e45)
![mqtt](https://github.com/ohAnd/dtuGateway/assets/145500978/9cbb1ff4-ed8c-4ef7-9b10-df6a13bbea72)

**Comment by smarthomehomebase** [comment]
Gibt es den Wirkungsgrad/Einstrahlung auch als Sensorwert?

**Comment by denkandich** [comment]
Hallo, habe jetz auf den letzten Snapshot gewechselt, aber das Interface schaut noch alt aus. In der Beschreibung lese ich
New 'dtuGateway web config interface' to configure all possible config parameter in one shot. Wo kann ich das finden ?.

**Comment by Lassa333** [comment]
Hi denkandich,

versuch doch bitte mal den Snapshot von gestern abend. Andreas war tätig und es könnte sein, dass dieser dein Probleme löst 😉

Ich würde mich freuen, über deine Fortschritte Bericht zu bekommen - Andreas sicherlich auch

**Comment by denkandich** [comment]
Wie schon im anderen Beitrag, wie komme ich zu dem Snapshot, bin wenig in der Sache drin, finde nur den alten Snapshot.

**Comment by Lassa333** [comment]
https://github.com/ohAnd/dtuGateway/actions/runs/9407361930
-------------------------------------------------------------------------------------------------
FreeMail powered by mail.de - MEHR SICHERHEIT, SERIOSITÄT UND KOMFORT

**Comment by denkandich** [comment]
Das ist das Problem, ich kann mit dem Link nichts machen, da ist keine bin die ich laden kann. Scheint ich mache das zu wenig.

**Comment by ohAnd** [comment]
Hi @denkandich ,

"einfach" das artefact herunterladen entpacken -> da ist das bin-file enthalten. (werde schauen den Namen von "artefact" auf sinnvolles noch zu ändern)

![image](https://github.com/ohAnd/dtuGateway/assets/15704728/a400fa99-cc0e-4d65-8644-27244b3728d2)

Da da das Thema noch recht "frisch" ist wird es erstmal auf einem feature branch bearbeitet und ist damit noch nicht ein latest snapshot, bis es eben grundsätzlich rund erscheint... Daher auch nur über diesen Weg zu erreichen. So ist es möglich das z.B. @Lassa333 so früh als möglich ins Testing (und spezifieren nochmal danke dafür ;-) ) gehen kann und trotzdem nicht selbst kompilieren braucht.

Gruss

btw. wenn es geht, bitte Fragen, Rückfragen, Anregungen im passenden Issue zu halten ggfs. ein neues eröffnen... wird sonst schnell schwierig dem Inhalt zu folgen

**Comment by Lassa333** [comment]
Guter Hinweis, ich habe gerade auch im anderen Post geantwortet. Ich stells hier nochmal ein - und wir testen hier weiter, OK?

Du hast die Version 1.6.0019_22 aktiv?

Bei der Version kannst du wieder (wie gewohnt) über die Einstellungen arbeiten. Versuch doch bitte mal folgendes:

in der Firmware: Unter Einstellungen -> bindings ganz runter scrollen und den Haken bei "Homeassistant Auto discovery" setzten. Speichern.

Bekommst du nun deinem Homeassistant eine neue Benachrichtigung, dass ein neues Gerät entdeckt wurde?

**Comment by ohAnd** [comment]
due to https://github.com/ohAnd/dtuGateway/issues/22#issuecomment-2156687287 - done
