### ISSUE TITLE
Hilfe Verstaendnis Datenbezug zum WR

### ISSUE THREAD

**Issue by BerndPetermanns** [ohAnd/dtuGateway#30]
Vielen Dank für dein Projekt.

Ich versuche mich aktuell etwas einzuarbeiten um das Ganze an meine Bedürfnisse anzupassen. Aber scheinbar scheitere ich am Verständnis. Ich würde dich bitten, mir kurz auf die Sprünge zu helfen.

Du nutzt in deiner Interface die Funktion: readRespAppGetHistPower(WiFiClient *localDtuClient). Hierbei zeigst du immer auf "localDtuClient". In der gateway.ino ist dies ein Objekt von WiFiClient dtuClient;. Aber dem dtuClient werden nie irgendwelche Werte zugewiesen.
Ich verstehe nicht ganz, wie der Bezug zu den Daten des WR zustande kommt. Da wird nirgends ein Port oder eine IP angegeben? Kannst du mir auf die Beine helfen, in den Quelltext hineinzukommen?

Vielen Dank
Petermanns

**Comment by ohAnd** [comment]
Hi @BerndPetermanns ,

Schau mal hier -> [https://github.com/ohAnd/dtuGateway/blob/26f68d8e49db6deeb11b5e82d6292584d012f064/src/dtuGateway.ino#L1481](https://github.com/ohAnd/dtuGateway/blob/26f68d8e49db6deeb11b5e82d6292584d012f064/src/dtuGateway.ino#L1481)

dort wird die Funktion aufgerufen und der dtuClient übergeben, sowie die gesetzte IP - Port ist hier nicht explizit angegeben, da als default im header [https://github.com/ohAnd/dtuGateway/blob/26f68d8e49db6deeb11b5e82d6292584d012f064/include/dtuInterface.h#L76](https://github.com/ohAnd/dtuGateway/blob/26f68d8e49db6deeb11b5e82d6292584d012f064/include/dtuInterface.h#L76) gesetzt. 

Und schliesslich wird dann hier [https://github.com/ohAnd/dtuGateway/blob/26f68d8e49db6deeb11b5e82d6292584d012f064/src/dtuInterface.cpp#L18](https://github.com/ohAnd/dtuGateway/blob/26f68d8e49db6deeb11b5e82d6292584d012f064/src/dtuInterface.cpp#L18)
die eigentliche Verbindung aufgebaut.

Gruss
