### ISSUE TITLE
Update in die cloud geht nicht immer

### ISSUE THREAD

**Issue by checkersky** [ohAnd/dtuGateway#47]
Hi, ich habe das Problem, dass die Updates in die Cloud nicht richtig funktionieren.

Obwohl bei mir die Cloud Pause ausgeschaltet ist, hab ich das Problem, dass wenn das Gateway läuft, ich teilweise keine Updates mehr in die Cloud bekomme.

Die letzte Person womit funktioniert hat, ist der Snapshot 1.90036 alle Versionen danach haben dieses Problem. Ich hab mal einen Screenshot abgehangen, wo man das ganz gut sehen kann.

Da gabe es ca. 3 Stunden kein Update in die cloud.

Im zweiten Screenshot sieht man auch, dass die Uhrzeit nicht mehren der Cloud Gehupdated wird .
Obwohl wir schon 14:30 Uhr haben, zeigt er noch 7:00 Uhr an.

Auch ist die Tagesmenge falsch das Gateway sagt 2 kWh in der Cloud nur 1,6 kWh.

![IMG_5959](https://github.com/user-attachments/assets/cda1010c-02f7-4247-8aa6-da2c47eb3684)
![IMG_5960](https://github.com/user-attachments/assets/33771725-b61d-4b2d-88b7-3d126826c364)

**Comment by checkersky** [comment]
![IMG_5959](https://github.com/user-attachments/assets/b0fae244-7b50-463c-8013-9cee6ca87f5b)
![IMG_5960](https://github.com/user-attachments/assets/9013d7e0-1d30-4a38-ba03-4a04ecb51698)

**Comment by checkersky** [comment]
Habe jetzt seit gestern dir Version dtuGateway_snapshot_1.9.0052_develop drauf damit funktioniert das Update in die Cloud wieder !

**Comment by ohAnd** [comment]
Hi @checkersky ,

"guter" Fehler, der sich von selbst heilt... ;-)
Habe in dem Bereich schon länger nichts mehr verändert. 
War aber der Meinung das in den letzten Tagen des Öfteren im Cloud-Service etwas "komisch" war...

Generell: wenn die Werte nicht geupdated werden, hat es nach meinen Erfahrungen mit einer "Belegung" der DTU um den Zeitpunkt alle 15 Minuten + ca. 7 Minuten zu tun ... die "cloud pause" hatte ich deswegen eingebaut, und verhindert Anfragen an die DTU < 30 und +10 sec um diese Zeitpunkte (15 min Takt) ... Wenn man es versucht zu verfolgen auf der Cloudseite, dann wird sehr schnell nach den Zeitpunkten der letzte timestamp in der cloud hochgezogen, aber die dazugehörigen Werte erst ca. 7 min später dargestellt ... 
Und wenn hier dann ein Powerset und "ausserplanmäßige" Anfrage reinrauscht, dann wird scheinbar nichts zur Cloud geposted...

**Comment by checkersky** [comment]
Oh.. ich dachte das die Cloud Pause genau das gegen teil macht also KEINE Daten zur Cloud senden.

Was aber noch schön wäre wenn da nicht über das ganze Display "Cloud Pause" steht sondern so wie im kleinen Oled Display nur ein Icon an geht. Eventuell als Option in den Einstellungen ?
