### ISSUE TITLE
OLED - more precision for total yield

### ISSUE THREAD

**Issue by ohAnd** [ohAnd/dtuGateway#50]
Hallo Andreas @ohAnd,

meinst Du, Du kannst in dem nächsten Release vielleicht die Ausgabe für den Totalertrag rechts unten im Display des OLEDs um eine Nachkommastelle ergänzen? 

Ist anscheinend in der display.cpp die Zeile mit: 
u8g2.drawStr(3 + 18 * 4 + offset_x, 56 + offset_y, ("t: " + String(lastDisplayData.totalYieldTotal, 0) + " kWh").c_str());

Das wäre schön! Ich habe doch nur so eine kleine PV-Anlage und es wird Herbst... 

Gruß
Frank

_Originally posted by @Frankyistda in https://github.com/ohAnd/dtuGateway/discussions/35#discussioncomment-10593540_

**Comment by Frankyistda** [comment]
Klappt! Im TFT Display jetzt eine Nachkommastelle für die Totalangabe! Super! Danke!
