### ISSUE TITLE
TFT display - cloud pause should be show as icon instead of full text

### ISSUE THREAD

**Issue by ohAnd** [ohAnd/dtuGateway#52]
Oh.. ich dachte das die Cloud Pause macht genau das gegen teil also KEINE Daten alle 15 min zur Cloud senden.

Was aber noch schön wäre wenn da nicht über das ganze Display "Cloud Pause" steht sondern so wie im kleinen Oled Display nur ein Icon an geht. Eventuell als Option in den Einstellungen ?

_Originally posted by @checkersky in https://github.com/ohAnd/dtuGateway/issues/47#issuecomment-2332727620_

**Comment by checkersky** [comment]
Habe gerade den neuen Snapshot installiert und das neue Cloud Icon sieht super aus.
Vielen dank dafür !!
