### ISSUE TITLE
Rote Sekunden Anzeige ausschalten

### ISSUE THREAD

**Issue by checkersky** [ohAnd/dtuGateway#57]
Hallo,

wäre es möglich eine Option einzubauen um die Sekunden Anzeige ausschalten ?
Also ich meine das so das man die Anzeige der Sekunden mit dem Roten Kreises abschalten kann.

**Comment by ohAnd** [comment]
Hi @checkersky ,

kleine Geschichte - bitte snapshot prüfen. ;-)

**Comment by checkersky** [comment]
Gerade getestet Funktioniert einwandfrei vielen dank !
